import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { Layout } from "@/components/layout";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({
    variable: "--font-inter-latin",
    subsets: ["latin"],
    fallback: ["Helvetica", "Arial", "sans-serif"],
})


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body
                    className={`${inter.variable} antialiased`}
                    style={{ fontFamily: "var(--font-inter-latin)", fontWeight: 400 }}
                >
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="dark"
                        enableSystem
                    >
                        <Toaster richColors />
                        <Layout>
                            {children}
                        </Layout>
                    </ThemeProvider>
                </body>
            </html>
        </ClerkProvider>
    );
}